export * from './ArrowRightSvg';
export * from './CalenderSvg';
export * from './DegreeSvg';
export * from './EducationSvg';
export * from './GithubSvg';
export * from './LinkedInSvg';
export * from './LocationSvg';
export * from './PointerSvg';
export * from './WorkSvg';
